#maria db

CREATE TABLE `t_message` (
  `MSG_KEY` varchar(14) NOT NULL,
  `NATION_CODE` varchar(10) NOT NULL,
  `MSG_TYPE` varchar(15) DEFAULT NULL,
  `MESSAGE` varchar(255) NOT NULL,
  PRIMARY KEY `PK_MESSAGE` (`MSG_KEY`,`NATION_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

insert into t_message( MSG_KEY,NATION_CODE,MSG_TYPE,MESSAGE ) values( 'LGN0000001', 'kr', 'LGN', 'Login'  );
insert into t_message( MSG_KEY,NATION_CODE,MSG_TYPE,MESSAGE ) values( 'LGN0000002', 'kr', 'LGN', '계정이 존재하지 않습니다'  );
insert into t_message( MSG_KEY,NATION_CODE,MSG_TYPE,MESSAGE ) values( 'LGN0000003', 'kr', 'LGN', '암호가 맞지 않습니다'  );
insert into t_message( MSG_KEY,NATION_CODE,MSG_TYPE,MESSAGE ) values( 'LGN0000004', 'kr', 'LGN', 'ID 저장'  );
insert into t_message( MSG_KEY,NATION_CODE,MSG_TYPE,MESSAGE ) values( 'LGN0000005', 'kr', 'LGN', 'ID(email)'  );
insert into t_message( MSG_KEY,NATION_CODE,MSG_TYPE,MESSAGE ) values( 'LGN0000006', 'kr', 'LGN', 'Password'  );
insert into t_message( MSG_KEY,NATION_CODE,MSG_TYPE,MESSAGE ) values( 'LGN0000007', 'kr', 'LGN', '로그인 정보를 입력하세요'  );
insert into t_message( MSG_KEY,NATION_CODE,MSG_TYPE,MESSAGE ) values( 'CFM0000001', 'kr', 'MSGBOX', 'Message'  );


CREATE TABLE `T_MEMBER` (
  MEMBER_ID varchar(30) NOT NULL,
  MEMBER_NM varchar(30) NOT NULL,
  MEMBER_TYPE VARCHAR(20) NOT NULL,
  PWD VARCHAR(255) NOT NULL,
  CHK_ID_CODE VARCHAR(255) NULL,
  CHK_PW_CODE VARCHAR(255) NULL,
  LOGIN_FAIL_CNT BIGINT(13) NOT NULL DEFAULT 0, 
  LAST_LOGIN_DT  DATETIME NULL, 
  LAST_LOGOUT_DT DATETIME NULL,
  UPT_DATE DATETIME,
  PRIMARY KEY `PK_MEMBER` (`MEMBER_ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO T_MEMBER ( MEMBER_ID, MEMBER_NM, MEMBER_TYPE, PWD ) VALUES ( 'letter20@nate.com', '정경진', 'ADMIN', 'QEuiVKRicPyKBDM1V5pGZw==!' );

CREATE TABLE `t_login_try` (
  `LOGIN_DATE` varchar(30) NOT NULL,
  `MEMBER_ID` varchar(30) NOT NULL,
  `IP_ADDR` varchar(20) DEFAULT NULL,
  `NIC_ADDR` varchar(30) DEFAULT NULL,
  `LOGIN_PW` varchar(50) NOT NULL,
  `SUCCESS_YN` varchar(1) NOT NULL,
  PRIMARY KEY (`LOGIN_DATE`,`MEMBER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE T_EXCEL_UPLOAD (
	EXCEL_KEY VARCHAR(15) NOT NULL,
	TITLE VARCHAR(15) NOT NULL,
	DATA_COUNT BIGINT(13) NOT NULL DEFAULT 0,	
	UPLOADER VARCHAR(30) NOT NULL,
	 PRIMARY KEY `PK_MESSAGE` (`EXCEL_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
;


CREATE TABLE T_EXCEL_UPLOAD_DATA (
	EXCEL_KEY VARCHAR(15) NOT NULL,
	DATA_SEQ  BIGINT(13) NOT NULL , 
	ADDRESS   VARCHAR(255) NOT NULL,
	IS_VALID_YN  VARCHAR(1) NOT NULL DEFAULT 'N',
	IS_TRANS_YN  VARCHAR(1) NOT NULL DEFAULT 'N' ,
	PRIMARY KEY `PK_EXCELUPLOADDATA` (EXCEL_KEY, DATA_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
;

CREATE TABLE `t_menu` (
  `MENU_CD` varchar(20) NOT NULL,
  `MENU_NM` varchar(255) NOT NULL,
  `UP_MENU_CD` varchar(20) NOT NULL,
  `ORDER_SEQ` bigint(13) DEFAULT 0,
  `PROGRAM_YN` varchar(1) NOT NULL DEFAULT 'Y',
  `MNU_ICON` varchar(30) DEFAULT NULL,
  `PROGRAM_URL` varchar(255) DEFAULT NULL,
  `DISPLAY_YN` varchar(1) DEFAULT 'Y',
  `DEL_YN` varchar(1) DEFAULT 'N',
  PRIMARY KEY (`MENU_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE T_GRANT (
	GRANT_CD VARCHAR(15) NOT NULL,
	GRANT_NM VARCHAR(50) NOT NULL,
	DEL_YN VARCHAR(1) NOT NULL,
	PRIMARY KEY `PK_GRANT` ( GRANT_CD )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO T_GRANT ( GRANT_CD, GRANT_NM, DEL_YN ) VALUES ( 'GNT202003171101', '최고 관리자', 'N' );
INSERT INTO T_GRANT ( GRANT_CD, GRANT_NM, DEL_YN ) VALUES ( 'GNT202003171102', '프로그램 관리자', 'N' );
INSERT INTO T_GRANT ( GRANT_CD, GRANT_NM, DEL_YN ) VALUES ( 'GNT202003171103', '업무 담당자', 'N' );

CREATE TABLE T_GRANT_MEMBER (
	GRANT_CD VARCHAR(15) NOT NULL,
	MEMBER_ID VARCHAR(30) NOT NULL,
	PRIMARY KEY `PK_GRANT_MEMBER` (GRANT_CD, MEMBER_ID) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;	

CREATE TABLE T_GRANT_MENU (
	GRANT_CD VARCHAR(15) NOT NULL,
	MENU_CD  VARCHAR(20) NOT NULL,
	GNT_CREATE VARCHAR(1) NULL,
	GNT_UPDATE VARCHAR(1) NULL,
	GNT_DELETE VARCHAR(1) NULL,
	GNT_POPUP  VARCHAR(1) NULL,
	PRIMARY KEY `PK_GRANT_MENU` (GRANT_CD, MENU_CD)  
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE T_ADDRESS_ROADNAME (
	ROAD_CODE VARCHAR(12) NOT NULL,
	ROAD_NM VARCHAR(80) NULL,
	ROAD_NM_ENG VARCHAR(80) NULL,
	SEQ VARCHAR(2) NOT NULL,
	SIDO_NM VARCHAR(20) NOT NULL,
	SIDO_NM_ENG VARCHAR(20) NULL,
	SIGUNGU_NM VARCHAR(40) NULL,
	SIGUNGU_NM_ENG VARCHAR(40) NULL,
	DONG_NM VARCHAR(20) NULL,
	DONG_NM_ENG VARCHAR(40) NULL,
	DONG_TYPE VARCHAR(1) NULL,
	DONG_CD  VARCHAR(3),
	USE_YN VARCHAR(1),
	CHG_REASON VARCHAR(1),
	CHG_HISTORY VARCHAR(14),
	CREATE_DATE VARCHAR(8),
	DELETE_DEAE VARCHAR(8),
	PRIMARY KEY `PK_ADDRESS_ROADNAME` (ROAD_CODE) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE T_CODE (
  `CD_KEY` varchar(20) NOT NULL,
  `CD_NAME` varchar(50) NOT NULL,
  `UPPER_CD_KEY` varchar(20) NOT NULL,
  `USE_YN` varchar(1) NOT NULL DEFAULT 'N',
  `REG_MEMBER` VARCHAR(30) NOT NULL,
  `REG_DATE` DATETIME ,
  PRIMARY KEY (`CD_KEY`,`UPPER_CD_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO T_CODE VALUES('LOCATION', '지역코드', '#' , 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('42', '강원도', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('41', '경기도', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('48', '경상남도', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('47', '경상북도', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('29', '광주광역시', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('27', '대구광역시', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('30', '대전광역시', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('26', '부산광역시', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('11', '서울특별시', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('36', '세종특별자치시', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('31', '울산광역시', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('28', '인천광역시', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('46', '전라남도', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('45', '전라북도', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('50', '제주특별자치도', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('44', '충청남도', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('43', '충청북도', 'LOCATION', 'Y', 'system', NOW());


CREATE TABLE T_ADDR_JIBUN (
	MNG_NO varchar(25) not null,
	MNG_SEQ VARCHAR(3) NOT NULL,
	COURT_DONG_CODE VARCHAR(10) NOT NULL, 
	SIDO_NM VARCHAR(20) NOT NULL,
	SIGUNGU_NM VARCHAR(20) NULL,
	COURT_UPMYUNDONG_NM VARCHAR(20) NULL,
	COURT_RI_NM VARCHAR(20) NULL,
	MOUNTAIN_YN VARCHAR(1) NULL,
	BUNJI VARCHAR(4) NULL,
	BUBUNJI VARCHAR(4) NULL,
	DELEGATE_YN VARCHAR(1) NULL,
	PRIMARY KEY PK_ADDR_JIBUN ( MNG_NO, MNG_SEQ ) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8; 


CREATE OR REPLACE TABLE T_ADDR_ENTRC (
	SIGUNGU_CD VARCHAR(5) NULL,
	ENTRY_SEQ VARCHAR(10) NULL,
	COURT_DONG_CODE VARCHAR(10) NOT NULL,
	SIDO_NM VARCHAR(40) NOT NULL,
	SIGUNGU_NM VARCHAR(40) NULL,
	UPMYUNDONG_NM VARCHAR(40) NULL,
	ROAD_CD VARCHAR(12) NOT NULL,
	ROAD_NM VARCHAR(80) NULL,
	BASEMENT_YN VARCHAR(1) NOT NULL,
	BUILDING_BONBUN VARCHAR(5) NOT NULL,
	BUILDING_BUBUN VARCHAR(5) NOT NULL,
	BUILDING_NAME VARCHAR(40) NULL,
	ZIPNUM VARCHAR(5) NULL,
	USE_DIV VARCHAR(100) NULL,
	BUILDING_GUN_YN VARCHAR(1) NULL,
	JURISDICTION_COURT_DONG VARCHAR(100) NULL,
	POS_X VARCHAR(25) NULL default '',
	POS_Y VARCHAR(25) NULL default '',
	PRIMARY KEY PK_ADDR_ENTRC(ROAD_CD, BASEMENT_YN,BUILDING_BONBUN, BUILDING_BUBUN, COURT_DONG_CODE )
)ENGINE=InnoDB DEFAULT CHARSET=utf8; 
;


CREATE TABLE `t_addr_road` (
  `MNG_NO` varchar(25) NOT NULL,
  `ROAD_CD` varchar(12) NOT NULL,
  `UPMYUNDONG_SEQ` varchar(2) NOT NULL,
  `BASEMENT_YN` varchar(1) DEFAULT NULL,
  `BUILDING_BONBUN` varchar(5) DEFAULT NULL,
  `BUILDING_BUBUN` varchar(5) DEFAULT NULL,
  `BASE_AREA_NO` varchar(5) DEFAULT NULL,
  `CHG_REASON_CD` varchar(2) DEFAULT NULL,
  `NOTIFY_DATE` varchar(8) DEFAULT NULL,
  `PREV_ROADADDR` varchar(25) DEFAULT NULL,
  `DETAIL_ADDR_EXIST_YN` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`MNG_NO`),
  KEY `IDX_ROADADDR` (`ROAD_CD`,`UPMYUNDONG_SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `t_address_roadname` (
  `ROAD_CODE` varchar(12) NOT NULL,
  `ROAD_NM` varchar(80) DEFAULT NULL,
  `ROAD_NM_ENG` varchar(80) DEFAULT NULL,
  `SEQ` varchar(2) NOT NULL,
  `SIDO_NM` varchar(20) NOT NULL,
  `SIDO_NM_ENG` varchar(20) DEFAULT NULL,
  `SIGUNGU_NM` varchar(40) DEFAULT NULL,
  `SIGUNGU_NM_ENG` varchar(40) DEFAULT NULL,
  `DONG_NM` varchar(20) DEFAULT NULL,
  `DONG_NM_ENG` varchar(40) DEFAULT NULL,
  `DONG_TYPE` varchar(1) DEFAULT NULL,
  `DONG_CD` varchar(3) DEFAULT NULL,
  `USE_YN` varchar(1) DEFAULT NULL,
  `CHG_REASON` varchar(1) DEFAULT NULL,
  `CHG_HISTORY` varchar(14) DEFAULT NULL,
  `CREATE_DATE` varchar(8) DEFAULT NULL,
  `DELETE_DEAE` varchar(8) DEFAULT NULL,
  PRIMARY KEY (`ROAD_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


