#maria db

CREATE TABLE `t_message` (
  `MSG_KEY` varchar(14) NOT NULL,
  `NATION_CODE` varchar(10) NOT NULL,
  `MSG_TYPE` varchar(15) DEFAULT NULL,
  `MESSAGE` varchar(255) NOT NULL,
  PRIMARY KEY `PK_MESSAGE` (`MSG_KEY`,`NATION_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

insert into t_message( MSG_KEY,NATION_CODE,MSG_TYPE,MESSAGE ) values( 'LGN0000001', 'kr', 'LGN', 'Login'  );
insert into t_message( MSG_KEY,NATION_CODE,MSG_TYPE,MESSAGE ) values( 'LGN0000002', 'kr', 'LGN', '계정이 존재하지 않습니다'  );
insert into t_message( MSG_KEY,NATION_CODE,MSG_TYPE,MESSAGE ) values( 'LGN0000003', 'kr', 'LGN', '암호가 맞지 않습니다'  );
insert into t_message( MSG_KEY,NATION_CODE,MSG_TYPE,MESSAGE ) values( 'LGN0000004', 'kr', 'LGN', 'ID 저장'  );
insert into t_message( MSG_KEY,NATION_CODE,MSG_TYPE,MESSAGE ) values( 'LGN0000005', 'kr', 'LGN', 'ID(email)'  );
insert into t_message( MSG_KEY,NATION_CODE,MSG_TYPE,MESSAGE ) values( 'LGN0000006', 'kr', 'LGN', 'Password'  );
insert into t_message( MSG_KEY,NATION_CODE,MSG_TYPE,MESSAGE ) values( 'LGN0000007', 'kr', 'LGN', '로그인 정보를 입력하세요'  );
insert into t_message( MSG_KEY,NATION_CODE,MSG_TYPE,MESSAGE ) values( 'CFM0000001', 'kr', 'MSGBOX', 'Message'  );


CREATE TABLE `T_MEMBER` (
  MEMBER_ID varchar(30) NOT NULL,
  MEMBER_NM varchar(30) NOT NULL,
  MEMBER_TYPE VARCHAR(20) NOT NULL,
  PWD VARCHAR(255) NOT NULL,
  CHK_ID_CODE VARCHAR(255) NULL,
  CHK_PW_CODE VARCHAR(255) NULL,
  LOGIN_FAIL_CNT BIGINT(13) NOT NULL DEFAULT 0, 
  LAST_LOGIN_DT  DATETIME NULL, 
  LAST_LOGOUT_DT DATETIME NULL,
  UPT_DATE DATETIME,
  PRIMARY KEY `PK_MEMBER` (`MEMBER_ID` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO T_MEMBER ( MEMBER_ID, MEMBER_NM, MEMBER_TYPE, PWD ) VALUES ( 'letter20@nate.com', '정경진', 'ADMIN', 'QEuiVKRicPyKBDM1V5pGZw==!' );

CREATE TABLE `t_login_try` (
  `LOGIN_DATE` varchar(30) NOT NULL,
  `MEMBER_ID` varchar(30) NOT NULL,
  `IP_ADDR` varchar(20) DEFAULT NULL,
  `NIC_ADDR` varchar(30) DEFAULT NULL,
  `LOGIN_PW` varchar(50) NOT NULL,
  `SUCCESS_YN` varchar(1) NOT NULL,
  PRIMARY KEY (`LOGIN_DATE`,`MEMBER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE t_excel_upload (
  EXCEL_KEY varchar(15) NOT NULL,
  TITLE varchar(15) NOT NULL,
  DATA_COUNT bigint(13) NOT NULL DEFAULT 0,
  UPLOADER varchar(30) NOT NULL,
  LOCATION_CODE varchar(20) NOT NULL,
  PHYSICAL_PATH varchar(255) DEFAULT NULL,
  ORIGINAL_FILE_NAME varchar(255) DEFAULT NULL,
  SAVED_FILE_NAME varchar(255) DEFAULT NULL,
  USE_YN varchar(255) DEFAULT NULL,
  UPLOAD_DT datetime DEFAULT NULL,
  PRIMARY KEY (EXCEL_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE t_excel_upload_data (
  EXCEL_KEY varchar(15) NOT NULL,
  DATA_SEQ bigint(13) NOT NULL,
  SIDO varchar(50) NOT NULL,
  SIGUNGU varchar(255) DEFAULT NULL,
  UPMYUNDONG varchar(255) DEFAULT NULL,
  RI varchar(255) DEFAULT NULL,
  BUNJI varchar(20) DEFAULT NULL,
  BUBUNJI varchar(20) DEFAULT NULL,
  PMU_CD varchar(16) DEFAULT NULL,
  IS_VALID_YN varchar(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (EXCEL_KEY,DATA_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `t_menu` (
  `MENU_CD` varchar(20) NOT NULL,
  `MENU_NM` varchar(255) NOT NULL,
  `UP_MENU_CD` varchar(20) NOT NULL,
  `ORDER_SEQ` bigint(13) DEFAULT 0,
  `PROGRAM_YN` varchar(1) NOT NULL DEFAULT 'Y',
  `MNU_ICON` varchar(30) DEFAULT NULL,
  `PROGRAM_URL` varchar(255) DEFAULT NULL,
  `DISPLAY_YN` varchar(1) DEFAULT 'Y',
  `DEL_YN` varchar(1) DEFAULT 'N',
  PRIMARY KEY (`MENU_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE T_GRANT (
	GRANT_CD VARCHAR(15) NOT NULL,
	GRANT_NM VARCHAR(50) NOT NULL,
	DEL_YN VARCHAR(1) NOT NULL,
	PRIMARY KEY `PK_GRANT` ( GRANT_CD )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO T_GRANT ( GRANT_CD, GRANT_NM, DEL_YN ) VALUES ( 'GNT202003171101', '최고 관리자', 'N' );
INSERT INTO T_GRANT ( GRANT_CD, GRANT_NM, DEL_YN ) VALUES ( 'GNT202003171102', '프로그램 관리자', 'N' );
INSERT INTO T_GRANT ( GRANT_CD, GRANT_NM, DEL_YN ) VALUES ( 'GNT202003171103', '업무 담당자', 'N' );

CREATE TABLE T_GRANT_MEMBER (
	GRANT_CD VARCHAR(15) NOT NULL,
	MEMBER_ID VARCHAR(30) NOT NULL,
	PRIMARY KEY `PK_GRANT_MEMBER` (GRANT_CD, MEMBER_ID) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;	

CREATE TABLE T_GRANT_MENU (
	GRANT_CD VARCHAR(15) NOT NULL,
	MENU_CD  VARCHAR(20) NOT NULL,
	GNT_CREATE VARCHAR(1) NULL,
	GNT_UPDATE VARCHAR(1) NULL,
	GNT_DELETE VARCHAR(1) NULL,
	GNT_POPUP  VARCHAR(1) NULL,
	PRIMARY KEY `PK_GRANT_MENU` (GRANT_CD, MENU_CD)  
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE T_CODE (
  `CD_KEY` varchar(20) NOT NULL,
  `CD_NAME` varchar(50) NOT NULL,
  `UPPER_CD_KEY` varchar(20) NOT NULL,
  `USE_YN` varchar(1) NOT NULL DEFAULT 'N',
  `REG_MEMBER` VARCHAR(30) NOT NULL,
  `REG_DATE` DATETIME ,
  PRIMARY KEY (`CD_KEY`,`UPPER_CD_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO T_CODE VALUES('LOCATION', '지역코드', '#' , 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('42', '강원도', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('41', '경기도', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('48', '경상남도', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('47', '경상북도', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('29', '광주광역시', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('27', '대구광역시', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('30', '대전광역시', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('26', '부산광역시', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('11', '서울특별시', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('36', '세종특별자치시', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('31', '울산광역시', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('28', '인천광역시', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('46', '전라남도', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('45', '전라북도', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('50', '제주특별자치도', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('44', '충청남도', 'LOCATION', 'Y', 'system', NOW());
INSERT INTO T_CODE VALUES('43', '충청북도', 'LOCATION', 'Y', 'system', NOW());

insert into t_code values ('DATA_STATUS', '데이터 상태', '#', 'Y', 'system', NOW()); 
insert into t_code values ('DS_REG', '등록완료', 'DATA_STATUS', 'Y', 'system', NOW());
insert into t_code values ('DS_POS_START', '좌표정보 동기화중', 'DATA_STATUS', 'Y', 'system', NOW());
insert into t_code values ('DS_POS_END', '좌표 동기화 완료', 'DATA_STATUS', 'Y', 'system', NOW());
insert into t_code values ('DS_INFO_START', '대지정보 동기화 중', 'DATA_STATUS', 'Y', 'system', NOW());
insert into t_code values ('DS_INFO_END', '대지정보 동기화 완료', 'DATA_STATUS', 'Y', 'system', NOW());


CREATE TABLE T_ADDR_JIBUN (
	MNG_NO varchar(25) not null,
	MNG_SEQ VARCHAR(3) NOT NULL,
	COURT_DONG_CODE VARCHAR(10) NOT NULL, 
	SIDO_NM VARCHAR(20) NOT NULL,
	SIGUNGU_NM VARCHAR(20) NULL,
	COURT_UPMYUNDONG_NM VARCHAR(20) NULL,
	COURT_RI_NM VARCHAR(20) NULL,
	MOUNTAIN_YN VARCHAR(1) NULL,
	BUNJI VARCHAR(4) NULL,
	BUBUNJI VARCHAR(4) NULL,
	DELEGATE_YN VARCHAR(1) NULL,
	PRIMARY KEY PK_ADDR_JIBUN ( MNG_NO, MNG_SEQ ) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8; 


CREATE TABLE T_BATCH_HISTORY_INFO (
   BATCH_KEY  VARCHAR(15) NOT NULL, 
   BATCH_TYPE VARCHAR(10) NOT NULL,
   BATCH_TARGET VARCHAR(15) NOT NULL,
   BATCH_START DATETIME NOT NULL,
   BATCH_END DATETIME NULL,
   SUCCESS_YN VARCHAR(1) NULL,
   DESCRIPT VARCHAR(500) NULL,
   PRIMARY KEY PK_BATCH_HISTORY (BATCH_KEY) 
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `t_jibun_info_data` (
  `DATA_KEY` varchar(20) NOT NULL COMMENT '데이터 키',
  `SIDO` varchar(50) DEFAULT NULL COMMENT '시도명',
  `SIGUNGU` varchar(50) DEFAULT NULL COMMENT '시군구',
  `UPMYUNDONG` varchar(50) DEFAULT NULL COMMENT '읍면동',
  `RI` varchar(50) DEFAULT NULL COMMENT '리',
  `MOUNTAIN_YN` varchar(1) DEFAULT NULL COMMENT '산여부',
  `BUNJI` varchar(4) DEFAULT NULL COMMENT '번지',
  `BUBUNJI` varchar(4) DEFAULT NULL COMMENT '부번지',
  `PNU` varchar(19) DEFAULT NULL COMMENT 'PNU_CD',
  `CRS` varchar(20) DEFAULT NULL COMMENT '좌표계',
  `X_POS` varchar(30) DEFAULT NULL COMMENT 'X 좌표',
  `Y_POS` varchar(30) DEFAULT NULL COMMENT 'Y 좌표',
  `LAND_WIDTH` varchar(10) DEFAULT NULL COMMENT '평수',
  `REG_DT` datetime DEFAULT NULL COMMENT '생성일자',
  `UPT_DT` datetime DEFAULT NULL COMMENT '수정일자',
  PRIMARY KEY (`DATA_KEY`),
  KEY `IDX_JIBUN_INFO` (`SIDO`,`SIGUNGU`,`UPMYUNDONG`,`RI`,`BUNJI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='지번정보 TABLE';


